###Add new booking userID
POST http://localhost:8000/api/booking/create/5ec098aed123b30664740b37
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWMwOThhZWQxMjNiMzA2NjQ3NDBiMzciLCJpYXQiOjE1ODk3NDMwMDN9.Av776-j-OUF4UPb6zAPFH4PyBDxRlZmvgwD_sjV3lA4

{
  "user": "5ec098aed123b30664740b37",
  "fromStation": "5ec0d494165aeb3ca4ab5e02",
  "toStation": "5ec0d4ca9cb2f03e240cd48e",
  "noOfAdultPassengers" : 2,
  "noOfChildPassengers" : 0,
  "pricePerAdultPassenger" : 25,
  "pricePerChildPassenger" : 18
}

###get all bookings
GET http://localhost:8000/api/bookings

###get all bookings by user id
GET http://localhost:8000/api/bookings/5ec098b8d123b30664740b38
